# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b143bfbf9f50d4f2b1de161483100174cd68f324eb69a579fa0866a31cbecda54e5556724e2d92e2324f4dc16c4870f4007c9580142491efa70620ba28b73ae

test:
  secret_key_base: de687f878985a7521418fa4006e8561b94468b5fe1781ed8d78c9391bdb0a2fa3af9761aba94fc36bfaea6ce41e48e98b4d0c46a03d0e74e3a0bdd252fb9f81a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
